server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: ${env}

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.guangxuan.model
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      table-underline: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false